r"""Exports the scan engine to the in-browser engine (frontend/src/lib/engine).

    python -m codeguard.browser_export          # rewrite rules.generated.json and parity.golden.json
    python -m codeguard.browser_export --check  # exit 1 if either file is stale (tests/test_browser_parity.py)

Python stays the single source of truth. rules.generated.json carries every rule, regex and constant the browser
engine needs, imported from the engine modules rather than retyped. parity.golden.json records what this engine
reports on a test corpus under browser semantics (no Bandit or Semgrep, the generic complexity heuristic for every
file, OSV off or mocked), and jest asserts the JavaScript engine reproduces it exactly.

Regexes become `new RegExp(pattern, "u")` sources with Python's semantics written out, because the dialects
disagree on Unicode: Python's \w is exactly [\p{L}\p{N}_], its \s includes U+001C-U+001F and U+0085 but not
U+FEFF, "." stops only at "\n", "$" also matches before a final newline, and IGNORECASE matches U+0130/U+0131 for
"i" while JS's i flag folds characters such as U+0345 into letters. IGNORECASE is therefore compiled into explicit
per-character sets computed from Python itself. Constructs without a faithful translation (\A, \Z, \B, atomic
groups, possessive quantifiers, conditionals, local or verbose flags, case-insensitive backreferences) raise.

Float results must not hinge on libm or summation details that differ between CPython builds and V8, so the golden
is rebuilt under Python 3.11 and 3.12 summation and with exp/log2 nudged a few ulps, and must come out identical.
"""
from __future__ import annotations

import argparse
import asyncio
import itertools
import json
import math
import re
import sys
import unicodedata
from contextlib import ExitStack, contextmanager
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Tuple
from unittest import mock

import httpx

from . import __version__
from . import engine as engine_mod
from . import scoring as scoring_mod
from . import sources as sources_mod
from . import suppressions as suppressions_mod
from .engine import OSV_ERROR, SCANNER_PRIORITY, SEV_RANK, disambiguate_fingerprints, scan
from .exporters import SARIF_LEVEL, SECURITY_SEVERITY, to_cyclonedx, to_sarif
from .models import _SUPPRESSION_TAIL, SEVERITIES, BugRisk, Dependency, Finding, SourceFile
from .scanners import complexity as complexity_mod
from .scanners import dependencies as deps_mod
from .scanners import patterns as patterns_mod
from .scanners import secrets as secrets_mod
from .scanners.dependencies import (
    collect_dependencies, cvss3_base_score, dependency_findings, enrich_with_osv, parse_vuln, severity_from_score,
)
from .scoring import grade_for, health_score, overall, security_score
from .sources import _make, _strip_common_prefix, detect_language, parse_github_url, should_skip
from .suppressions import parse as parse_suppressions
from .taxonomy import CWE_TO_OWASP, OWASP_TOP10, owasp_for_cwe

BACKEND = Path(__file__).resolve().parent.parent
ENGINE_DIR = BACKEND.parent / "frontend" / "src" / "lib" / "engine"
RULES_PATH = ENGINE_DIR / "rules.generated.json"
GOLDEN_PATH = ENGINE_DIR / "parity.golden.json"
FIXTURES = BACKEND / "tests" / "fixtures"
CORPUS_DIR = FIXTURES / "parity"
REGEN = "cd backend && python -m codeguard.browser_export"
NOTE = f"GENERATED by `{REGEN}` from backend/codeguard. Do not edit: change the Python engine and regenerate."

# Provider-format values are assembled from parts at generation time, so no literal is ever committed (GitHub push
# protection blocks those). Corpus files and the golden hold the placeholder; the golden carries the parts too.
PLACEHOLDERS: Dict[str, List[str]] = {
    "__FAKE_STRIPE_KEY__": ["sk_", "live_", "51HxT2cAbCdEfGhIjKlMnOpQr"],  # the value tests/conftest.py uses
    "__FAKE_STRIPE_RESTRICTED__": ["rk_", "test_", "parityFixture0123456789ab"],
    "__FAKE_AWS_KEY_ID__": ["AK", "IA", "PARITY0FIXTURE12"],
    "__FAKE_AWS_SECRET__": ["parityFixtureSecret/", "0123456789+abcdefghi"],
    "__FAKE_GITHUB_TOKEN__": ["gh", "p_", "parityFixture0123456789abcdefghijklmn"],
    "__FAKE_GITHUB_PAT__": ["github", "_pat_", "11PARITYFIXTURE0_", "parityFixture0123456789abcdefghijklmnopqrstuvwxyz"],
    "__FAKE_GOOGLE_KEY__": ["AI", "za", "SyParityFixture0123456789abcdefghij"],
    "__FAKE_SLACK_TOKEN__": ["xo", "xb-", "123456789012-parityFixture"],
    "__FAKE_SLACK_WEBHOOK__": ["https://hooks.", "slack.com/services/", "T0PARITY1/", "B0PARITY2/", "parityFixtureSecret123"],
    "__FAKE_OPENAI_KEY__": ["sk-", "proj-", "abcdEFGH1234ijklMNOP", "T3Blbk", "FJ", "qrstUVWX5678yzABCDEF"],
    "__FAKE_ANTHROPIC_KEY__": ["sk-", "ant-", "api03-", "parityFixture0123456789abcdefghijklmnopqrstuvwxyz",
                               "ABCDEFGHIJKLMNOPQRSTUVWXYZ012345"],
    "__FAKE_GROQ_KEY__": ["gs", "k_", "parityFixture0123456789abcdefghijklmnopqrstuvwxyzAB"],
    "__FAKE_PRIVATE_KEY_HEADER__": ["-----BEGIN ", "RSA PRIVATE", " KEY-----"],
    "__FAKE_JWT__": ["eyJ", "hbGciOiJIUzI1NiJ9", ".", "eyJ", "zdWIiOiJwYXJpdHkifQ", ".", "c2lnbmF0dXJlLXBhcml0eS10ZXN0"],
    "__FAKE_DB_URL__": ["postgres", "://admin:", "Pr0dP4ss!", "@db.internal:5432/app"],
    "__FAKE_REDIS_URL__": ["redis", "://default:", "s3cr3tR3dis", "@cache:6379/0"],
    "__FAKE_DB_URL_PLACEHOLDER__": ["postgres", "://user:", "<password>", "@db/app"],
    "__FAKE_DB_URL_ENV__": ["mongodb+srv", "://app:", "${DB_PASS}", "@cluster0.example.net/prod"],
}


def substitute(text: str) -> str:
    for name, parts in PLACEHOLDERS.items():
        text = text.replace(name, "".join(parts))
    return text

# ------------------------------------------------------------------------------------------- regex dialect


class Untranslatable(ValueError):
    """A Python regex construct with no faithful JavaScript translation."""


WORD = r"\p{L}\p{N}_"
WORD_BOUNDARY = f"(?:(?<=[{WORD}])(?![{WORD}])|(?<![{WORD}])(?=[{WORD}]))"
SYNTAX = set("^$\\.*+?()[]{}|/")
CLASS_SPECIAL = set("\\]-[^")
SIMPLE_ESCAPES = {"n": 0x0A, "t": 0x09, "r": 0x0D, "f": 0x0C, "v": 0x0B, "a": 0x07}
INLINE_FLAGS = {"i": re.IGNORECASE, "m": re.MULTILINE, "s": re.DOTALL, "u": re.UNICODE}
SUPPORTED_FLAGS = int(re.IGNORECASE | re.MULTILINE | re.DOTALL | re.UNICODE)  # int: ~RegexFlag only spans defined flags
REPEAT = re.compile(r"\{([0-9]*)(,?)([0-9]*)\}")  # sre_parse: "{}" and "{x" are literals, "{,n}" is 0..n


@lru_cache(maxsize=1)
def _every_char() -> str:
    return "".join(chr(cp) for cp in range(0x110000) if not 0xD800 <= cp <= 0xDFFF)


@lru_cache(maxsize=1)
def python_whitespace() -> Tuple[int, ...]:
    """Code points Python's \\s, str.split() and str.strip() treat as whitespace."""
    cps = tuple(ord(c) for c in re.findall(r"\s", _every_char()))
    assert cps == tuple(ord(c) for c in _every_char() if c.isspace()), "re's \\s and str.isspace() disagree"
    return cps


@lru_cache(maxsize=1)
def python_line_breaks() -> Tuple[int, ...]:
    """Code points str.splitlines() breaks on (it also treats CR LF as one break)."""
    return tuple(cp for cp in range(0x110000) if not 0xD800 <= cp <= 0xDFFF and len(f"a{chr(cp)}b".splitlines()) == 2)


@lru_cache(maxsize=None)
def _case_delta(atom: str) -> Tuple[Tuple[int, ...], Tuple[int, ...]]:
    """Characters Python's IGNORECASE adds to and removes from a one-character atom."""
    every = _every_char()
    added = re.findall(f"(?i)(?!(?-i:{atom})){atom}", every)
    removed = re.findall(f"(?i)(?!{atom})(?-i:{atom})", every)
    return tuple(map(ord, added)), tuple(map(ord, removed))


def _char(cp: int, in_class: bool) -> str:
    ch = chr(cp)
    if ch in "\n\t\r":
        return {"\n": r"\n", "\t": r"\t", "\r": r"\r"}[ch]
    if cp < 0x20 or cp >= 0x7F:
        return f"\\u{{{cp:x}}}"
    return "\\" + ch if ch in (CLASS_SPECIAL if in_class else SYNTAX) else ch


def _ranges(cps) -> str:
    """A compact class body for a set of code points."""
    cps, out = sorted(cps), []
    for _, run in itertools.groupby(enumerate(cps), key=lambda t: t[1] - t[0]):
        run = [cp for _, cp in run]
        out.append(_char(run[0], True) if len(run) == 1 else
                   _char(run[0], True) + ("" if len(run) == 2 else "-") + _char(run[-1], True))
    return "".join(out)


class _Translator:
    def __init__(self, pattern: str, flags: int):
        self.p, self.i, self.flags = pattern, 0, int(flags)
        self.space = _ranges(python_whitespace())

    def fail(self, why: str):
        raise Untranslatable(f"{why} at offset {self.i} in {self.p!r}")

    def _escape_cp(self, in_class: bool) -> Optional[int]:
        """Consume an escape that denotes a single code point; None (cursor untouched) if it is not one."""
        p, i = self.p, self.i
        c = p[i + 1]
        if c in SIMPLE_ESCAPES or (c == "b" and in_class):
            self.i = i + 2
            return SIMPLE_ESCAPES.get(c, 0x08)
        for prefix, width in (("x", 2), ("u", 4), ("U", 8)):
            if c == prefix:
                self.i = i + 2 + width
                return int(p[i + 2:self.i], 16)
        if c == "N":
            end = p.index("}", i)
            self.i = end + 1
            return ord(unicodedata.lookup(p[i + 3:end]))
        if c == "0" or (in_class and c in "1234567"):
            digits = re.match(r"[0-7]{1,3}", p[i + 1:]).group(0)
            self.i = i + 1 + len(digits)
            return int(digits, 8)
        if c.isascii() and not c.isalnum():
            self.i = i + 2
            return ord(c)
        return None

    def _class_cp(self) -> int:
        if self.p[self.i] == "\\":
            cp = self._escape_cp(in_class=True)
            if cp is None:
                self.fail("unsupported escape in a set")
            return cp
        self.i += 1
        return ord(self.p[self.i - 1])

    def _class(self) -> str:
        start = self.i
        self.i += 1
        negate = self.p.startswith("^", self.i)
        self.i += negate
        items: List[str] = []
        cats = set()
        first = True
        while True:
            if self.i >= len(self.p):
                self.fail("unterminated set")
            if self.p[self.i] == "]" and not first:
                self.i += 1
                break
            first = False
            if self.p[self.i] == "\\" and self.p[self.i + 1] in "wWdDsS":
                cats.add(self.p[self.i + 1])
                self.i += 2
                continue
            lo = self._class_cp()
            if self.p.startswith("-", self.i) and not self.p.startswith("-]", self.i):
                self.i += 1
                items.append(_char(lo, True) + "-" + _char(self._class_cp(), True))
            else:
                items.append(_char(lo, True))
        source = self.p[start:self.i]
        if cats & set("WS"):
            if cats in ({"s", "S"}, {"w", "W"}) and not items:
                return r"[^\s\S]" if negate else r"[\s\S]"
            self.fail(r"negated class escape (\W, \S) inside a set")
        body = "".join(items) + "".join({"w": WORD, "d": r"\p{Nd}", "D": r"\P{Nd}", "s": self.space}[c] for c in sorted(cats))
        out = ("[^" if negate else "[") + body + "]"
        if self.flags & re.IGNORECASE:
            added, removed = _case_delta(source)
            if added:
                out = f"[{body}{_ranges(added)}]" if not negate else f"(?:{out}|[{_ranges(added)}])"
            if removed:
                out = f"(?:(?![{_ranges(removed)}]){out})"
        return out

    def _literal(self, cp: int) -> str:
        if self.flags & re.IGNORECASE:
            added, removed = _case_delta(re.escape(chr(cp)))
            if removed:
                self.fail("IGNORECASE removes characters from a literal")
            if added:
                return f"[{_ranges((cp, *added))}]"
        return _char(cp, False)

    def _group(self) -> str:
        p, i = self.p, self.i
        if not p.startswith("(?", i):
            self.i += 1
            return "("
        for same in ("(?:", "(?=", "(?!", "(?<=", "(?<!"):
            if p.startswith(same, i):
                self.i += len(same)
                return same
        if p.startswith("(?P<", i):
            end = p.index(">", i)
            name = p[i + 4:end]
            if not re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name):
                self.fail(f"group name {name!r} is not a JavaScript identifier")
            self.i = end + 1
            return f"(?<{name}>"
        if p.startswith("(?P=", i):
            if self.flags & re.IGNORECASE:
                self.fail("case-insensitive backreference")
            end = p.index(")", i)
            self.i = end + 1
            return f"\\k<{p[i + 4:end]}>"
        if p.startswith("(?#", i):
            self.i = p.index(")", i) + 1
            return ""
        self.fail("atomic group, conditional or inline flags")

    def translate(self) -> str:
        p = self.p
        lead = re.match(r"\(\?([a-zA-Z]+)\)", p)
        if lead:
            for f in lead.group(1):
                self.flags |= int(INLINE_FLAGS.get(f, 1 << 30))
            self.i = lead.end()
        if self.flags & ~SUPPORTED_FLAGS:
            self.fail("unsupported flag (only IGNORECASE, MULTILINE and DOTALL translate)")
        out: List[str] = []
        repeatable = False
        while self.i < len(p):
            ch = p[self.i]
            m = REPEAT.match(p, self.i) if ch == "{" else None
            if ch == "\\":
                nxt = p[self.i + 1]
                if nxt in "AZBGz":
                    self.fail(f"\\{nxt} has no faithful JavaScript translation")
                if nxt in "wWdDsSb":
                    out.append({"w": f"[{WORD}]", "W": f"[^{WORD}]", "d": r"\p{Nd}", "D": r"\P{Nd}",
                                "s": f"[{self.space}]", "S": f"[^{self.space}]", "b": WORD_BOUNDARY}[nxt])
                    self.i += 2
                    repeatable = nxt != "b"
                    continue
                if nxt in "123456789":
                    if self.flags & re.IGNORECASE:
                        self.fail("case-insensitive backreference")
                    ref = re.match(r"[0-9]{1,2}", p[self.i + 1:]).group(0)
                    out.append("\\" + ref)
                    self.i += 1 + len(ref)
                    repeatable = True
                    continue
                cp = self._escape_cp(in_class=False)
                if cp is None:
                    self.fail(f"unsupported escape \\{nxt}")
                out.append(self._literal(cp))
                repeatable = True
            elif ch == "[":
                out.append(self._class())
                repeatable = True
            elif ch == "(":
                out.append(self._group())
                repeatable = False
            elif ch in ")|.^$":
                out.append({")": ")", "|": "|", ".": r"[\s\S]" if self.flags & re.DOTALL else r"[^\n]",
                            "^": r"(?<![^\n])" if self.flags & re.MULTILINE else "^",
                            "$": r"(?=\n|(?![\s\S]))" if self.flags & re.MULTILINE else r"(?=\n?(?![\s\S]))"}[ch])
                self.i += 1
                repeatable = ch in ")."
            elif ch in "*+?" or (m and (m.group(1) or m.group(2))):
                if not repeatable:
                    self.fail("nothing to repeat")
                if m:
                    lo, comma, hi = m.groups()
                    out.append("{" + (lo or "0") + comma + hi + "}")
                    self.i = m.end()
                else:
                    out.append(ch)
                    self.i += 1
                if p.startswith("+", self.i):
                    self.fail("possessive quantifier")
                if p.startswith("?", self.i):
                    out.append("?")
                    self.i += 1
                repeatable = False
            else:
                out.append(self._literal(ord(ch)))
                self.i += 1
                repeatable = True
        return "".join(out)


def py_flags(flags: int) -> str:
    return "".join(f for f, bit in INLINE_FLAGS.items() if f != "u" and flags & bit)


def regex(rx, call: str, flags: int = 0) -> dict:
    """A JS regex spec for a compiled pattern (or pattern string). `call` is how Python applies it: "match" specs
    are anchored here, so exec/test reproduce re.match; findall/finditer/sub/split need a "g" flag added."""
    pattern, flags = (rx.pattern, int(rx.flags) & ~int(re.UNICODE)) if isinstance(rx, re.Pattern) else (rx, flags)
    re.compile(pattern, flags)
    source = _Translator(pattern, flags).translate()
    if call == "match":
        source = f"^(?:{source})"
    return {"pattern": source, "flags": "u", "call": call, "python": {"pattern": pattern, "flags": py_flags(flags)}}

# ------------------------------------------------------------------------------------------------ rules


def build_rules() -> dict:
    s, sup, cx, dp = sources_mod, suppressions_mod, complexity_mod, deps_mod
    pair = lambda t: {"above": t[0], "points": t[1]}  # noqa: E731
    browser = asyncio.run(scan([], use_bandit=False, use_semgrep=False, use_osv=False, radon=False))
    return {
        "$comment": NOTE,
        "version": __version__,
        "regex": {
            "doc": ("Compile with new RegExp(pattern, flags). Python's semantics are spelled out in the source (see "
                    "codeguard/browser_export.py): every spec uses the 'u' flag and never JS's i/m/s flags. 'call' "
                    "is how Python applies it: 'match' sources are already anchored; add 'g' for findall, finditer, "
                    "sub and split. Match offsets are UTF-16 indexes, Python's are code points."),
            "word": f"[{WORD}]",
        },
        "python": {
            "doc": ("Python str semantics the engine relies on. strip()/split() use 'whitespace'; splitlines() "
                    "breaks on 'line_breaks' and treats CR LF as one break; len() and slicing count code points."),
            "whitespace": list(python_whitespace()),
            "line_breaks": list(python_line_breaks()),
        },
        "taxonomy": {"owasp_top10": OWASP_TOP10, "cwe_to_owasp": {f"CWE-{k}": v for k, v in sorted(CWE_TO_OWASP.items())}},
        "sources": {
            "languages": s.LANGUAGES,
            "special_names": s.SPECIAL_NAMES,
            "env_prefix": ".env",
            "skip_dirs": sorted(s.SKIP_DIRS),
            "skip_files": sorted(s.SKIP_FILES),
            "requirements_file": regex(s.REQUIREMENTS_FILE, "match"),
            "unscanned_suffixes": list(s.UNSCANNED_SUFFIXES),
            "non_code": sorted(s.NON_CODE),
            "binary_sniff": s.BINARY_SNIFF,
            "zip_junk": s.ZIP_JUNK,
            "max_files": s.DEFAULT_MAX_FILES,
            "max_file_bytes": s.MAX_FILE_BYTES,
            "max_total_bytes": s.MAX_TOTAL_BYTES,
            "max_members": s.MAX_MEMBERS,
            "max_download_bytes": s.MAX_DOWNLOAD_BYTES,
            "github_url": regex(s.GITHUB_URL, "match"),
        },
        "patterns": {
            "comment_prefixes": list(patterns_mod.COMMENT_PREFIXES),
            "max_line": patterns_mod.MAX_LINE,
            "description_chars": patterns_mod.DESCRIPTION_CHARS,
            "snippet_chars": patterns_mod.SNIPPET_CHARS,
            "rules": [{
                "id": r.id, "title": r.title, **{k: v for k, v in regex(r.pattern, "search", r.flags).items() if k != "call"},
                "severity": r.severity, "cwe": r.cwe, "owasp": owasp_for_cwe(r.cwe), "recommendation": r.recommendation,
                "languages": sorted(r.languages), "bandit_overlap": r.bandit_overlap,
            } for r in patterns_mod.RULES],
        },
        "secrets": {
            "max_line": secrets_mod.MAX_LINE,
            "signatures": [{"id": rid, "title": title, **{k: v for k, v in regex(rx, "search").items() if k != "call"},
                            "severity": sev} for rid, title, rx, sev in secrets_mod.SIGNATURES],
            "generic": {**regex(secrets_mod.GENERIC, "search"), "name_group": 1, "value_group": 3},
            "db_url": {"rule": "SEC-DB-URL", "password_group": 4},
            "placeholder_hints": list(secrets_mod.PLACEHOLDER_HINTS),
            "min_distinct": secrets_mod.MIN_DISTINCT,
            "min_entropy": secrets_mod.MIN_ENTROPY,
            "recommendation": secrets_mod.RECOMMENDATION,
            "redact": {"min_length": secrets_mod.REDACT_MIN, "head": secrets_mod.REDACT_HEAD,
                       "tail": secrets_mod.REDACT_TAIL, "mask": secrets_mod.REDACT_MASK},
        },
        "suppressions": {
            "marker": sup.MARKER,
            "token": regex(sup.TOKEN, "finditer"),
            "leaders": list(sup.LEADERS),
            "leader_prefix": sorted(sup.LEADER_PREFIX),
            "closers": list(sup.CLOSERS),
            "tail": regex(sup.TAIL, "match"),
            "max_marker_line": sup.MAX_MARKER_LINE,
            "all": sup.ALL,
            "escaped": regex(sup.ESCAPED, "sub"),
            "quotes": list(sup.QUOTES),
            "multiline_delims": {k: list(v) for k, v in sup.MULTILINE_DELIMS.items()},
            "malformed": sup.MALFORMED,
        },
        "fingerprint": {"suppression_tail": regex(_SUPPRESSION_TAIL, "sub")},
        "engine": {
            "severities": SEVERITIES,
            "severity_rank": SEV_RANK,
            "scanner_priority": SCANNER_PRIORITY,
            "scanners_run": browser.scanners_run,
            "engine_version": f"browser-{__version__}",
            "osv_error": OSV_ERROR,
        },
        "complexity": {
            "decision": regex(cx.DECISION, "findall"),
            "func": regex(cx.FUNC, "findall"),
            "empty_catch": regex(cx.EMPTY_CATCH, "findall"),
            "comments": regex(cx.COMMENTS, "sub"),
            "string_literal": regex(cx.STRING_LITERAL, "sub"),
            "todo": regex(cx.TODO, "search"),
            "rank_cutoffs": [list(t) for t in cx.RANK_CUTOFFS],
            "large_file": pair(cx.LARGE_FILE), "moderate_file": pair(cx.MODERATE_FILE),
            "very_high_cc": pair(cx.VERY_HIGH_CC), "high_cc": pair(cx.HIGH_CC), "high_avg_cc": pair(cx.HIGH_AVG_CC),
            "deep_nesting": pair(cx.DEEP_NESTING), "nested": pair(cx.NESTED),
            "long_line": cx.LONG_LINE, "long_lines": pair(cx.LONG_LINES), "todos": pair(cx.TODOS),
            "empty_handler": {"points": cx.EMPTY_HANDLER[0], "cap": cx.EMPTY_HANDLER[1]},
            "risk_levels": [list(t) for t in cx.RISK_LEVELS],
        },
        "dependencies": {
            "osv_batch": dp.OSV_BATCH,
            "osv_vuln": dp.OSV_VULN,
            "osv_batch_size": dp.OSV_BATCH_SIZE,
            "osv_concurrency": dp.OSV_CONCURRENCY,
            "max_detail_lookups": dp.MAX_DETAIL_LOOKUPS,
            "version": regex(dp.VERSION, "search"),
            "non_registry": list(dp.NON_REGISTRY),
            "requirement": regex(dp.REQUIREMENT, "match"),
            "requirement_skip": list(dp.REQUIREMENT_SKIP),
            "pinning_ops": list(dp.PINNING_OPS),
            "go_require": regex(dp.GO_REQUIRE, "match"),
            "requirements_file": regex(dp.REQUIREMENTS_FILE, "match"),
            "version_split": regex(dp.VERSION_SPLIT, "split"),
            "cvss_weights": dp._W,
            "privileges_required": {"unchanged": dp._PR[False], "changed": dp._PR[True]},
            "severity_cutoffs": [list(t) for t in dp.SEVERITY_CUTOFFS],
            "ghsa_severity": dp.GHSA_SEVERITY,
            "sev_order": dp.SEV_ORDER,
            "cwe": dp.DEP_CWE,
            "owasp": owasp_for_cwe(dp.DEP_CWE),
            "dep_line": {"doc": "prefix + name with regex syntax characters escaped + suffix",
                         "prefix": regex(dp.DEP_LINE[0], "search"), "suffix": regex(dp.DEP_LINE[1], "search")},
        },
        "scoring": {
            "weights": scoring_mod.WEIGHTS,
            "decay": scoring_mod.DECAY,
            "health_per_risk": scoring_mod.HEALTH_PER_RISK,
            "blend": list(scoring_mod.BLEND),
            "grades": [list(t) for t in scoring_mod.GRADES],
        },
        "exporters": {"sarif_level": SARIF_LEVEL, "security_severity": SECURITY_SEVERITY},
    }


def iter_regexes(node: Any, path: str = "") -> Iterator[Tuple[str, dict]]:
    """Every regex spec in the rules, keyed by dotted path (list items by their id). lang.js mirrors this."""
    if isinstance(node, dict):
        if "pattern" in node and "flags" in node:
            yield path, node
        for k, v in node.items():
            if k != "python":
                yield from iter_regexes(v, f"{path}.{k}" if path else k)
    elif isinstance(node, list):
        for i, v in enumerate(node):
            yield from iter_regexes(v, f"{path}.{v['id'] if isinstance(v, dict) and 'id' in v else i}")

# ----------------------------------------------------------------------------------------------- corpus


def load_corpus() -> Dict[str, str]:
    """path -> content (with placeholders), sorted by code point: the order files are handed to scan()."""
    files: Dict[str, str] = {}
    for base, prefix in ((FIXTURES / "vulnerable_app", "vulnerable_app/"), (CORPUS_DIR, "")):
        for p in base.rglob("*"):
            rel = unicodedata.normalize("NFC", p.relative_to(base).as_posix())
            if p.is_file() and not rel.startswith("_"):
                files[prefix + rel] = p.read_bytes().decode("utf-8")
    files.update(json.loads((CORPUS_DIR / "_virtual.json").read_text(encoding="utf-8"))["files"])
    assert not any(re.fullmatch(r"[0-9]+", k) for k in files), "integer-like keys would reorder in JSON.parse"
    return dict(sorted(files.items()))


def browser_files(corpus: Dict[str, str]) -> List[SourceFile]:
    """What the browser loaders hand the engine: skip-listed and unknown paths dropped, then sources._make."""
    out = []
    for path, content in corpus.items():
        if not should_skip(path) and detect_language(path):
            f = _make(path, substitute(content).encode("utf-8"))
            if f:
                out.append(f)
    return out


def _scan(files: List[SourceFile], use_osv: bool = False):
    return asyncio.run(scan(files, use_bandit=False, use_semgrep=False, use_osv=use_osv, radon=False))


def _report(report) -> dict:
    out = report.model_dump(mode="json")
    del out["duration_ms"]
    return out


def _cyclonedx(deps: List[Dependency]) -> dict:
    bom = to_cyclonedx(deps, "parity")
    del bom["serialNumber"], bom["metadata"]["timestamp"]
    return bom


def _assert_coverage(report) -> None:
    seen = {f.rule_id for f in report.security_issues + report.suppressed_issues}
    wanted = [r.id for r in patterns_mod.RULES] + [rid for rid, *_ in secrets_mod.SIGNATURES] + ["SEC-GENERIC"]
    missing = [rid for rid in wanted if rid not in seen]
    if missing:
        raise SystemExit(f"the parity corpus no longer triggers {missing}: add a positive case under {CORPUS_DIR}")

# ------------------------------------------------------------------------------------------- OSV (mocked)


def _osv_mock() -> dict:
    return json.loads((CORPUS_DIR / "_osv.json").read_text(encoding="utf-8"))


@contextmanager
def _mocked_osv(mock_data: dict, fail: bool = False):
    """Route engine.scan's OSV lookups to an in-memory transport; yields the recorded requests."""
    requests: List[dict] = []

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/v1/querybatch":
            queries = json.loads(request.content)["queries"]
            requests.append({"method": "POST", "url": str(request.url), "json": {"queries": queries}})
            if fail:
                return httpx.Response(503)
            ids = [mock_data["batch"].get(f"{q['package']['ecosystem']}/{q['package']['name']}@{q['version']}") for q in queries]
            return httpx.Response(200, json={"results": [{"vulns": [{"id": i} for i in v]} if v else {} for v in ids]})
        requests.append({"method": "GET", "url": str(request.url)})
        detail = mock_data["vulns"].get(request.url.path.rsplit("/", 1)[-1])
        return httpx.Response(200, json=detail) if detail else httpx.Response(404, json={"code": 5, "message": "Bug not found."})

    client = httpx.AsyncClient(transport=httpx.MockTransport(handler))

    async def enrich(deps):
        return await enrich_with_osv(deps, client)

    try:
        with mock.patch.object(engine_mod, "enrich_with_osv", enrich):
            yield requests
    finally:
        asyncio.run(client.aclose())


def osv_section(corpus: Dict[str, str]) -> dict:
    mock_data = _osv_mock()
    manifests = [f for f in browser_files(corpus) if collect_dependencies([f])]
    with _mocked_osv(mock_data) as requests:
        report = _scan(manifests, use_osv=True)
    with _mocked_osv(mock_data, fail=True), mock.patch.object(deps_mod.log, "disabled", True):
        outage = _scan(manifests, use_osv=True)
    reason = re.compile(r"\(.*\)$", re.S)
    outage_errors = [reason.sub("(<reason>)", e) for e in outage.errors]
    return {
        "doc": ("scan(manifests, osv on) with fetch mocked from 'mock': POST osv_batch {queries} answers "
                "{results: [{vulns: [{id}]} or {}]}; GET osv_vuln answers mock.vulns[id] or 404. Detail GETs run "
                "concurrently, so compare their URLs as a set. In 'outage' the batch POST answers 503 and each error's "
                "parenthesised reason is normalised to '(<reason>)'."),
        "mock": mock_data,
        "manifests": [f.path for f in manifests],
        "requests": requests,
        "report": _report(report),
        "sarif": to_sarif(report.security_issues, report.suppressed_issues),
        "cyclonedx": _cyclonedx(report.dependencies),
        "outage": {**_report(outage), "errors": outage_errors},
    }

# ---------------------------------------------------------------------------------------- Python semantics


def naive_sum(items, start=0):
    """builtin sum() of CPython <= 3.11: plain left-to-right addition."""
    total = start
    for x in items:
        total = total + x
    return total


def neumaier_sum(items, start=0):
    """builtin sum() of CPython >= 3.12: Neumaier-compensated over floats, exact over an all-int prefix."""
    it = iter(items)
    total = start
    for x in it:
        if type(total) is int and type(x) in (int, bool):
            total += x
            continue
        total = total + x
        break
    else:
        return total
    c = 0.0
    for x in it:
        if type(total) is not float or type(x) not in (float, int, bool):
            total = total + x
        elif type(x) is float:
            t = total + x
            c += (total - t) + x if abs(total) >= abs(x) else (x - t) + total
            total = t
        else:
            total += float(x)
    return total + c if type(total) is float and c and math.isfinite(c) else total


class _NudgedMath:
    """`math` with exp/log2 off by a few ulps, standing in for another libm (V8 differs from glibc by <= 2)."""

    def __init__(self, ulps: int):
        self.ulps = ulps

    def __getattr__(self, name):
        return getattr(math, name)

    def _nudge(self, x: float) -> float:
        for _ in range(abs(self.ulps)):
            x = math.nextafter(x, math.inf if self.ulps > 0 else -math.inf)
        return x

    def exp(self, x):
        return math.exp(x) if x == 0 else self._nudge(math.exp(x))

    def log2(self, x):
        exact = math.log2(x)
        return exact if exact.is_integer() else self._nudge(exact)  # powers of two are exact in every libm


FLOAT_MODELS = ("builtin", "naive_sum", "neumaier_sum", "libm_up", "libm_down")


@contextmanager
def float_model(name: str):
    with ExitStack() as stack:
        if name.endswith("_sum"):
            impl = naive_sum if name == "naive_sum" else neumaier_sum
            for mod in (engine_mod, scoring_mod, secrets_mod, complexity_mod, deps_mod):
                stack.enter_context(mock.patch.object(mod, "sum", impl, create=True))
        elif name.startswith("libm"):
            nudged = _NudgedMath(3 if name == "libm_up" else -3)
            for mod in (scoring_mod, secrets_mod):
                stack.enter_context(mock.patch.object(mod, "math", nudged))
        yield

# ------------------------------------------------------------------------------------------------ vectors

CVSS_METRICS = [("AV", "NALP"), ("AC", "LH"), ("PR", "NLH"), ("UI", "NR"), ("S", "UC"), ("C", "HLN"), ("I", "HLN"), ("A", "HLN")]


def _inputs() -> dict:
    """Vector inputs live beside the corpus, so CodeGuard's self-scan of backend/codeguard never reports test data."""
    return json.loads((CORPUS_DIR / "_vectors.json").read_text(encoding="utf-8"))


def _source_file_vector(path: str, runs: List[list]) -> dict:
    """`content` stays as [piece, count] runs, which keeps the 1000-character cases small."""
    f = _make(path, "".join(piece * n for piece, n in runs).encode("utf-8"))
    return {"path": path, "content": runs, "file": {**f.model_dump(), "content": runs} if f else None}


def _parse_github(url: str):
    try:
        return list(parse_github_url(url))
    except sources_mod.SourceError:
        return None


def _parsed(result) -> dict:
    return {"by_line": {str(n): [{"rules": sorted(d.rules), "marker_line": d.marker_line, "justification": d.justification}
                                 for d in ds] for n, ds in sorted(result.by_line.items())},
            "warnings": result.warnings}


def _finding(severity: str) -> Finding:
    return Finding(rule_id="x", scanner="patterns", severity=severity, type="t", description="d", file_path="a", recommendation="r")


def _risk(score: float) -> BugRisk:
    return BugRisk(file_path="a", risk_score=score, complexity="low", issues=[])


def _fingerprint_vectors(inputs: dict) -> dict:
    out = []
    for rule, path, line, source, snippet in inputs["fingerprints"]:
        f = Finding(rule_id=rule, scanner="patterns", severity="high", type="t", description="d", file_path=path,
                    line_number=line, recommendation="r", snippet=snippet)
        out.append({"rule_id": rule, "file_path": path, "line_number": line, "source_line": source, "snippet": snippet,
                    "fingerprint": f.with_fingerprint(source_line=source).fingerprint})
    family = [Finding(rule_id=r, scanner="patterns", severity="high", type="t", description="d", file_path=p,
                      line_number=n, recommendation="r", fingerprint=fp) for r, p, n, fp in inputs["disambiguate"]]
    before = [f.fingerprint for f in family]
    disambiguate_fingerprints(family)
    return {"doc": "Finding.with_fingerprint(source_line); then engine.disambiguate_fingerprints over a family.",
            "cases": out,
            "disambiguate": [{"rule_id": f.rule_id, "file_path": f.file_path, "line_number": f.line_number,
                              "before": b, "after": f.fingerprint} for f, b in zip(family, before, strict=True)]}


def _dependency_vectors(corpus: Dict[str, str], inputs: dict) -> dict:
    mock_data = _osv_mock()
    manifests = [f for f in browser_files(corpus) if collect_dependencies([f])]
    parse = [{"path": p, "content": c, "deps": [d.model_dump(mode="json") for d in collect_dependencies(
        [SourceFile(path=p, content=c, language="config", lines=c.count("\n") + 1)])]} for p, c in inputs["manifests"]]
    by_key = {f"{d.ecosystem}/{d.name}@{d.version}": d for f in manifests for d in collect_dependencies([f])}
    vulns = []
    for key, ids in mock_data["batch"].items():
        for vid in ids:
            dep = by_key[key]
            detail = mock_data["vulns"].get(vid, {"id": vid})
            vulns.append({"detail": detail, "dep": dep.model_dump(mode="json"), "vuln": parse_vuln(detail, dep).model_dump(mode="json")})
    vulns += [{"detail": d, "dep": dep, "vuln": parse_vuln(d, Dependency.model_validate(dep)).model_dump(mode="json")}
              for d, dep in inputs["parse_vuln_extra"]]
    injected = [Dependency.model_validate(d) for d in inputs["injected_deps"]]
    files = [f for f in manifests if f.path in ("deps/package.json", "deps/requirements.txt")]
    return {
        "clean_version": [[v, deps_mod._clean_version(v)] for v in inputs["clean_version"]],
        "version_key": [[v, list(deps_mod._version_key(v))] for v in inputs["version_key"]],
        "parse": parse,
        "cvss3_base_score": [[v, cvss3_base_score(v)] for v in inputs["cvss"]],
        "cvss3_exhaustive": {
            "doc": "Every CVSS:3.1 base vector: metrics in order, values nested like itertools.product (last varies fastest).",
            "metrics": [[k, list(v)] for k, v in CVSS_METRICS],
            "scores": [cvss3_base_score("CVSS:3.1/" + "/".join(f"{k}:{c}" for (k, _), c in zip(CVSS_METRICS, combo, strict=True)))
                       for combo in itertools.product(*[v for _, v in CVSS_METRICS])]},
        "severity_from_score": [[s, severity_from_score(s)] for s in inputs["severity_scores"]],
        "parse_vuln": vulns,
        "dependency_findings": {
            "deps": [d.model_dump(mode="json") for d in injected],
            "files": [{"path": f.path, "content": f.content} for f in files],
            "findings": [f.model_dump(mode="json") for f in dependency_findings(injected, files)],
        },
        "cyclonedx": _cyclonedx(injected),
        "purl": [[d.name, d.version, d.ecosystem, d.purl] for d in injected + [
            Dependency(name="x", version="", ecosystem="Cargo", manifest="m")]],
    }


def _scan_vectors(inputs: dict) -> dict:
    return {
        "doc": ("Direct scanner calls (before the engine re-fingerprints from source). Secret contents use "
                "placeholders; substitute them before scanning."),
        "scan_patterns": [{"content": c, "path": p, "language": lang, "skip_bandit_overlap": False, "findings": [
            f.model_dump(mode="json") for f in patterns_mod.scan_patterns(c, p, lang)]} for c, p, lang in inputs["scan_patterns"]],
        "scan_secrets": [{"content": c, "path": p, "findings": [
            f.model_dump(mode="json") for f in secrets_mod.scan_secrets(substitute(c), p)]} for c, p in inputs["scan_secrets"]],
    }


def build_vectors(corpus: Dict[str, str]) -> dict:
    inputs = _inputs()
    rules = build_rules()
    probes = inputs["regex_probes"]
    regex_results = {}
    for key, spec in iter_regexes(rules):
        py = re.compile(spec["python"]["pattern"], sum(INLINE_FLAGS[f] for f in spec["python"]["flags"]))
        apply = py.match if spec.get("call") == "match" else py.search
        regex_results[key] = {str(i): [m.start(), m.end(), list(m.groups())] for i, s in enumerate(probes) if (m := apply(s))}
    fixed = inputs["fixed"]
    security_cases, health_cases = inputs["security_cases"], inputs["health_cases"]
    return {
        "doc": ("Unit vectors. Floats marked 'rounded10' were rounded to 10 decimals because unrounded libm/sum "
                "results differ in the last ulp between CPython builds and V8: compare round(js, 10) or |diff| < 1e-9."),
        "sources": {
            "paths": [{"path": p, "language": detect_language(p), "skip": should_skip(p)} for p in inputs["paths"]],
            "strip_common_prefix": [{"paths": ps, "prefix": _strip_common_prefix(ps)} for ps in inputs["strip_common_prefix"]],
            "make_source_file": [_source_file_vector(p, runs) for p, runs in inputs["make_source_file"]],
            "decode_utf8": [{"bytes": b, "text": bytes(b).decode("utf-8", errors="ignore")} for b in inputs["decode_utf8"]],
            "github_url": [{"url": u, "parsed": _parse_github(u)} for u in inputs["github_urls"]],
        },
        "python": {
            "strings": [{"s": s, "strip": s.strip(), "lstrip": s.lstrip(), "rstrip": s.rstrip(), "split": s.split(),
                         "splitlines": s.splitlines(), "len": len(s)} for s in inputs["strings"]],
            "slices": [{"s": s, "start": a, "end": b, "result": s[a:b]} for s, a, b in inputs["slices"]],
            "fixed": [{"x": x, "digits": n, "text": f"{x:.{n}f}"} for x, n in fixed],
            "round": [{"x": x, "digits": n, "result": round(x, n)} for x, n in fixed if n],
            "sum": [{"items": xs, "neumaier": neumaier_sum(xs), "naive": naive_sum(xs)} for xs in inputs["sums"]],
        },
        "regex": {"doc": ("For every spec in the rules (keys as lang.js regexSpecs builds them): the probes it matches, as "
                          "probe index -> [start, end, groups] in code points; it must not match any other probe."),
                  "probes": probes, "results": regex_results},
        "patterns": {"is_comment": [[line, patterns_mod._is_comment(line)] for line in inputs["is_comment"]], **_scan_vectors(inputs)},
        "secrets": {
            "shannon_entropy_rounded10": [[v, round(secrets_mod.shannon_entropy(v), 10)] for v in inputs["entropy"]],
            "redact": [[v, secrets_mod.redact(v)] for v in inputs["redact"]],
            "looks_placeholder": [[v, secrets_mod._looks_placeholder(v)] for v in inputs["looks_placeholder"]],
        },
        "suppressions": [{"content": c, "path": p, "language": lang, **_parsed(parse_suppressions(c, p, lang))}
                         for c, p, lang in inputs["suppressions"]],
        "fingerprints": _fingerprint_vectors(inputs),
        "complexity": {"rank": [[cc, complexity_mod._rank(cc)] for cc in range(0, 46)],
                       "analyze_file": [{"content": c, "path": p, "language": lang, "risk": complexity_mod.analyze_file(
                           c, p, lang, heuristic=True).model_dump(mode="json")} for c, p, lang in inputs["complexity"]]},
        "dependencies": _dependency_vectors(corpus, inputs),
        "scoring": {
            "security_score_rounded10": [[sevs, round(security_score([_finding(s) for s in sevs]), 10)] for sevs in security_cases],
            "health_score_rounded10": [[risks, n, round(health_score([_risk(r) for r in risks], n), 10)] for risks, n in health_cases],
            "overall": [{"severities": sevs, "risk_scores": risks, "total_files": n,
                         "result": list(overall([_finding(s) for s in sevs], [_risk(r) for r in risks], n))}
                        for sevs, (risks, n) in zip(security_cases, (health_cases * 2)[:len(security_cases)], strict=True)],
            "grade_for": [[s, grade_for(s)] for s in inputs["grade_scores"]],
        },
    }


# ---------------------------------------------------------------------------------------------- golden


def _golden_core(corpus: Dict[str, str]) -> dict:
    files = browser_files(corpus)
    report = _scan(files)
    _assert_coverage(report)
    return {
        "expected": {
            "files": [{"path": f.path, "language": f.language, "lines": f.lines} for f in files],
            "report": _report(report),
            "sarif": to_sarif(report.security_issues, report.suppressed_issues),
            "cyclonedx": _cyclonedx(report.dependencies),
        },
        "expected_osv": osv_section(corpus),
        "vectors": build_vectors(corpus),
    }


def _first_difference(a: Any, b: Any, path: str = "golden") -> str:
    if isinstance(a, dict) and isinstance(b, dict) and a.keys() == b.keys():
        return next((_first_difference(a[k], b[k], f"{path}.{k}") for k in a if a[k] != b[k]), path)
    if isinstance(a, list) and isinstance(b, list) and len(a) == len(b):
        return next((_first_difference(x, y, f"{path}[{i}]") for i, (x, y) in enumerate(zip(a, b, strict=True)) if x != y), path)
    return f"{path} ({a!r} vs {b!r})"


def build_golden() -> dict:
    corpus = load_corpus()
    variants = {}
    for name in FLOAT_MODELS:
        with float_model(name):
            variants[name] = _golden_core(corpus)
    base = variants["builtin"]
    for name, got in variants.items():
        if got != base:
            raise SystemExit(f"the golden changes under the '{name}' float model at {_first_difference(base, got)}: a "
                             f"value sits on a rounding boundary, so CPython 3.11/3.12 or V8 could disagree. Adjust it.")
    return {
        "$comment": NOTE,
        "version": __version__,
        "procedure": (
            "For each corpus entry in key order: content = substitute placeholders (join the parts); skip it if "
            "shouldSkip(path) or !detectLanguage(path); file = makeSourceFile(path, content), dropped when null. "
            "expected.files lists what that yields (lines as makeSourceFile counts them, before newline "
            "normalisation). Scan the files with Bandit/Semgrep absent, OSV off and the generic complexity heuristic "
            "for every file; expected.report is the result minus duration_ms. expected.sarif = toSarif(security_issues, "
            "suppressed_issues). expected.cyclonedx = toCycloneDx(dependencies, 'parity') minus the volatile fields."),
        "volatile": {
            "report": ["duration_ms"],
            "cyclonedx": ["serialNumber (urn:uuid:<uuid4>)", "metadata.timestamp (ISO 8601, UTC)"],
            "doc": "Removed from expected output: delete the same keys from the JavaScript output before comparing.",
        },
        "scan_options": {"bandit": False, "semgrep": False, "osv": False, "complexity": "heuristic",
                         "skip_bandit_overlap": False, "scanners_run": base["expected"]["report"]["scanners_run"]},
        "placeholders": PLACEHOLDERS,
        "corpus": corpus,
        **base,
    }

# ----------------------------------------------------------------------------------------- self-checks


def secret_hits(texts: Dict[str, str]) -> List[str]:
    """Places where a provider signature matches: none may exist in anything committed."""
    hits = []
    for name, text in texts.items():
        for rid, _, rx, _ in secrets_mod.SIGNATURES:
            if re.search(rx, text):
                hits.append(f"{name}: {rid}")
    return hits


def _strings(node: Any) -> Iterator[str]:
    if isinstance(node, str):
        yield node
    elif isinstance(node, dict):
        for k, v in node.items():
            yield k
            yield from _strings(v)
    elif isinstance(node, list):
        for v in node:
            yield from _strings(v)


def check_no_secrets(outputs: Dict[Path, str], golden: dict) -> None:
    texts = {str(p): text for p, text in outputs.items()}
    texts.update({f"golden string #{i}": s for i, s in enumerate(_strings(golden))})
    own = [Path(__file__), BACKEND / "tests" / "test_browser_parity.py"]
    for p in list(CORPUS_DIR.rglob("*")) + list((FIXTURES / "vulnerable_app").rglob("*")) + own:
        if p.is_file():
            texts[str(p)] = p.read_text(encoding="utf-8")
    hits = secret_hits(texts)
    if hits:
        raise SystemExit("provider-format secret literal(s) would be committed; build them from PLACEHOLDERS:\n  "
                         + "\n  ".join(hits[:20]))


def render(obj: dict) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=True) + "\n"


def build() -> Dict[Path, str]:
    golden = build_golden()
    outputs = {RULES_PATH: render(build_rules()), GOLDEN_PATH: render(golden)}
    check_no_secrets(outputs, golden)
    return outputs


def stale(outputs: Dict[Path, str]) -> List[Path]:
    return [p for p, text in outputs.items() if not p.exists() or p.read_text(encoding="utf-8") != text]


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m codeguard.browser_export", description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if a generated file is out of date")
    args = parser.parse_args(argv)
    outputs = build()
    if args.check:
        out_of_date = stale(outputs)
        for p in out_of_date:
            print(f"{p.relative_to(BACKEND.parent)} is stale: run `{REGEN}`", file=sys.stderr)
        return 1 if out_of_date else 0
    ENGINE_DIR.mkdir(parents=True, exist_ok=True)
    for p, text in outputs.items():
        p.write_text(text, encoding="utf-8")
        print(f"wrote {p.relative_to(BACKEND.parent)} ({len(text) // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
